FROM python:3.12-slim

ENV PIP_NO_CACHE_DIR=1

RUN apt-get update && apt-get install -y --no-install-recommends \
    curl ca-certificates \
    fonts-noto fonts-noto-cjk fonts-noto-color-emoji \
    libmagic1 file \
    && rm -rf /var/lib/apt/lists/* && apt-get clean

RUN python -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

COPY services/kdcube-ai-app/requirements-chat.txt requirements.txt

RUN pip install --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt && \
    python3 -m playwright install --with-deps chromium

RUN mkdir "/workspace"
WORKDIR "/workspace"

ENTRYPOINT ["/opt/venv/bin/python3"]