bundles:
  version: "1"
  items:
    - id: "versatile@2026-03-31-13-36"
      config:
        preferences:
          auto_capture: true
          max_recent_events: 25
          widget_max_events: 15
        execution:
          runtime:
            mode: docker
        integrations:
          telegram:
            enabled: false
            webhook_url: "<domain name>/assembly.yaml service route/<tenant>/<project>/api/public/<alias>"
            send_responses: true
            stream_activity: true
            web_app_auth_max_age_seconds: 86400
        visibility:
          bundle:
            allowed_roles: []
          api:
            telegram_user_admin_data:
              roles:
                - kdcube:role:super-admin
            telegram_user_admin_upsert:
              roles:
                - kdcube:role:super-admin
            telegram_user_admin_delete:
              roles:
                - kdcube:role:super-admin
        ui:
          web_app_widgets:
            versatile_webapp:
              src_folder: ui/widgets/versatile_webapp
              build_command: npm install --no-package-lock && OUTDIR=<VI_BUILD_DEST_ABSOLUTE_PATH> npm run build
        mcp:
          preferences:
            auth:
              header_name: X-Versatile-Preferences-MCP-Token
          services: {}
