# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Elena Viter

"""Named service provider SDK surface.

This package owns the transport-neutral provider/client contract. The first
implementation is local async dispatch; API, MCP, and Data Bus adapters should
delegate to the same types and registry instead of redefining operation shapes.
"""

from __future__ import annotations

from kdcube_ai_app.apps.chat.sdk.infra.auth_context import AuthContext

from kdcube_ai_app.apps.chat.sdk.solutions.named_services_providers.admission import (
    ADMISSION_MODE_APPLICATION,
    ADMISSION_MODE_DELEGATED,
    DELEGATED_SELECTOR_AGENT,
    DELEGATED_SELECTOR_BEARER,
    NamedServiceAdmission,
    NamedServiceAdmissionDecision,
    NamedServiceAdmissionSelector,
    effective_named_service_operation,
)

from .agent_instructions import (
    compose_named_service_agent_instructions,
    named_service_agent_instruction_block,
)
from .client_tools import (
    NAMED_SERVICE_TOOLS_ALIAS,
    NAMED_SERVICE_TOOLS_MODULE,
    client_has_named_service_tools,
    compose_named_service_react_instructions,
    connected_named_service_namespaces,
    denied_named_service_namespaces,
    extend_tool_specs_for_named_services,
    named_service_agent_event_source_namespaces,
    named_service_agent_pull_namespaces,
    render_named_service_namespace_roster,
    named_service_canvas_resolver_namespaces,
    named_service_namespace_client_resolver_config,
    named_service_namespace_client_tools_config,
    named_service_namespace_config,
    named_service_namespace_provider_configs,
    named_service_namespace_provider_configs_from_config,
    named_service_namespaces,
    named_services_config,
    named_service_tool_spec,
)
from .canvas_resolver import (
    NamedServiceCanvasObjectResolver,
    register_configured_named_service_canvas_resolvers,
)
from .artifact_rehoster import (
    NamedServiceArtifactNamespaceRehoster,
    register_configured_named_service_artifact_rehosters,
)
from .block_policy_adapter import (
    NAMED_SERVICE_BLOCK_PRODUCTION_POLICY_ID,
    NAMED_SERVICE_EVENT_SOURCE_PREFIX,
    named_service_event_source_id,
    register_configured_named_service_event_sources,
)
from .boundary_policy import (
    NamedServiceBoundaryCatalog,
    NamespaceBoundaryPolicy,
    as_list,
    as_mapping,
    clean_namespace,
)
from .discovery import (
    ConfiguredNamedServiceDiscovery,
    DEFAULT_DISCOVERY_TTL_SECONDS,
    NAMED_SERVICE_DISCOVERY_SCHEMA,
    NamedServiceDiscoveryEntry,
    RedisNamedServiceDiscovery,
    bind_named_service_discovery,
    fetch_namespace_intros,
    get_current_named_service_discovery,
    publish_registry_discovery,
)
from .client import NamedServiceClient
from .instructions import NAMED_SERVICES_REACT_ADDITIONAL_INSTRUCTIONS
from .provider import NamedServiceProvider, named_service_provider
from .registry import NamedServiceRegistry
from kdcube_ai_app.apps.chat.sdk.solutions.named_services_providers.schema_projection import (
    SCHEMA_PROJECTION_CONTRACT,
    SCHEMA_VIEW_CATALOG,
    SCHEMA_VIEW_FULL,
    SCHEMA_VIEW_KIND,
    SCHEMA_VIEW_OPERATION,
    SCHEMA_VIEW_SEARCH,
    SchemaProjectionError,
    build_schema_catalog,
    build_schema_search,
    build_schema_tree,
    project_schema,
    project_schema_response,
    project_schema_response_async,
)
from .transports.api_client import (
    ENDPOINT_TRANSPORT_BUNDLE_OPERATION,
    ENDPOINT_TRANSPORT_BUNDLE_REGISTRY,
    ENDPOINT_TRANSPORT_MODULE,
    NamedServiceEndpoint,
    call_named_service_endpoint,
    call_named_service_endpoint_stream,
)
from .transports.api import (
    NamedServiceApiTransport,
    dispatch_named_service_api_request,
    dispatch_named_service_api_stream_request,
)
from .types import (
    NAMED_SERVICE_RESPONSE_SCHEMA,
    NAMED_SERVICE_REQUEST_SCHEMA,
    SOURCE_BUNDLE_ID_METADATA,
    TRANSPORT_API,
    TRANSPORT_DATA_BUS,
    TRANSPORT_LOCAL,
    TRANSPORT_MCP,
    BLOCK_PRODUCE,
    BLOCK_RENDER,
    EVENT_ACTION,
    EVENT_RESOLVE,
    OBJECT_HOST_FILE,
    OBJECT_SCHEMA,
    NamedServiceContext,
    NamedServiceError,
    NamedServiceOperationSpec,
    NamedServiceProviderSpec,
    NamedServiceRequest,
    NamedServiceResponse,
    NamedServiceSearchScope,
    NamedServiceStreamResult,
    build_default_operations,
    normalize_search_scopes,
    namespace_for_ref,
)

__all__ = [
    "NAMED_SERVICES_REACT_ADDITIONAL_INSTRUCTIONS",
    "NAMED_SERVICE_REQUEST_SCHEMA",
    "NAMED_SERVICE_RESPONSE_SCHEMA",
    "SOURCE_BUNDLE_ID_METADATA",
    "NAMED_SERVICE_TOOLS_ALIAS",
    "NAMED_SERVICE_TOOLS_MODULE",
    "NAMED_SERVICE_BLOCK_PRODUCTION_POLICY_ID",
    "NAMED_SERVICE_DISCOVERY_SCHEMA",
    "NAMED_SERVICE_EVENT_SOURCE_PREFIX",
    "DEFAULT_DISCOVERY_TTL_SECONDS",
    "TRANSPORT_API",
    "TRANSPORT_DATA_BUS",
    "TRANSPORT_LOCAL",
    "TRANSPORT_MCP",
    "ENDPOINT_TRANSPORT_BUNDLE_OPERATION",
    "ENDPOINT_TRANSPORT_BUNDLE_REGISTRY",
    "ENDPOINT_TRANSPORT_MODULE",
    "BLOCK_PRODUCE",
    "BLOCK_RENDER",
    "EVENT_ACTION",
    "EVENT_RESOLVE",
    "OBJECT_HOST_FILE",
    "OBJECT_SCHEMA",
    "SCHEMA_PROJECTION_CONTRACT",
    "SCHEMA_VIEW_CATALOG",
    "SCHEMA_VIEW_FULL",
    "SCHEMA_VIEW_KIND",
    "SCHEMA_VIEW_OPERATION",
    "SCHEMA_VIEW_SEARCH",
    "AuthContext",
    "ADMISSION_MODE_APPLICATION",
    "ADMISSION_MODE_DELEGATED",
    "DELEGATED_SELECTOR_AGENT",
    "DELEGATED_SELECTOR_BEARER",
    "NamedServiceAdmission",
    "NamedServiceAdmissionDecision",
    "NamedServiceAdmissionSelector",
    "NamedServiceApiTransport",
    "NamedServiceBoundaryCatalog",
    "ConfiguredNamedServiceDiscovery",
    "NamedServiceEndpoint",
    "NamedServiceArtifactNamespaceRehoster",
    "NamedServiceCanvasObjectResolver",
    "NamedServiceClient",
    "NamedServiceContext",
    "NamedServiceDiscoveryEntry",
    "NamedServiceError",
    "NamedServiceOperationSpec",
    "NamedServiceProvider",
    "NamedServiceProviderSpec",
    "NamedServiceRegistry",
    "NamedServiceRequest",
    "NamedServiceResponse",
    "NamedServiceSearchScope",
    "NamedServiceStreamResult",
    "NamespaceBoundaryPolicy",
    "SchemaProjectionError",
    "build_schema_catalog",
    "build_schema_search",
    "build_schema_tree",
    "build_default_operations",
    "as_list",
    "as_mapping",
    "clean_namespace",
    "normalize_search_scopes",
    "call_named_service_endpoint",
    "call_named_service_endpoint_stream",
    "client_has_named_service_tools",
    "compose_named_service_agent_instructions",
    "compose_named_service_react_instructions",
    "named_service_agent_instruction_block",
    "connected_named_service_namespaces",
    "denied_named_service_namespaces",
    "render_named_service_namespace_roster",
    "dispatch_named_service_api_request",
    "dispatch_named_service_api_stream_request",
    "extend_tool_specs_for_named_services",
    "named_service_agent_event_source_namespaces",
    "named_service_agent_pull_namespaces",
    "named_service_canvas_resolver_namespaces",
    "named_service_provider",
    "named_service_event_source_id",
    "named_service_namespace_client_tools_config",
    "named_service_namespace_client_resolver_config",
    "named_service_namespace_config",
    "named_service_namespace_provider_configs",
    "named_service_namespace_provider_configs_from_config",
    "named_service_namespaces",
    "named_services_config",
    "named_service_tool_spec",
    "namespace_for_ref",
    "effective_named_service_operation",
    "register_configured_named_service_canvas_resolvers",
    "register_configured_named_service_artifact_rehosters",
    "register_configured_named_service_event_sources",
    "RedisNamedServiceDiscovery",
    "publish_registry_discovery",
    "project_schema",
    "project_schema_response",
    "project_schema_response_async",
    "bind_named_service_discovery",
    "get_current_named_service_discovery",
]
